start-at-login = true

gaps.inner.horizontal = 2
gaps.inner.vertical = 2

gaps.outer.left = 2
gaps.outer.bottom = 2
gaps.outer.top = 2
gaps.outer.right = 2

[mode.main.binding]
alt-ctrl-slash = 'mode cmd'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-9 = 'workspace 9'
alt-c = 'workspace C'
alt-g = 'workspace G'
alt-m = 'workspace M'
alt-q = 'workspace Q'
alt-s = 'workspace S'
alt-w = 'workspace W'
alt-x = 'workspace X'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-g = 'move-node-to-workspace G'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-x = 'move-node-to-workspace X'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor next --wrap-around'

alt-slash = 'layout tiles horizontal vertical'

[mode.cmd.binding]
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
r = ['reload-config', 'mode main']
minus = 'resize smart -50'
space = 'resize smart +50'
esc = ['mode main']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'
9 = 'secondary'
Q = 'secondary'
S = 'secondary'

# WezTerm
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace W'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace G'

# Mail
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.fmgjjmmmlfnkbppncabfkddbjimcfncm'
run = 'move-node-to-workspace M'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace M'

# Safari
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace S'

# Slack
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 9'

# Logseq
[[on-window-detected]]
if.app-id = 'com.electron.logseq'
run = 'move-node-to-workspace Q'

# Xcode
[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = 'move-node-to-workspace X'

# ChatGPT
[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace C'
