#!/bin/sh

cd ~

sh -c "$(curl -fsSL https://git.io/zinit-install)"
yadm checkout .zshrc
zsh -c "source ~/.zshrc"

brew install --HEAD nvim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim -E -c PlugInstall -c qa

brew install gpg
yadm decrypt
