#!/bin/sh

cd ~

sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
# yadm checkout .zshrc
zsh -c "source ~/.zshrc"

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim -E -c PlugInstall -c qa

brew install gpg
yadm decrypt
