require 'plugins.statusline'
require 'plugins.syntax'
require 'plugins.completion'
require 'plugins.lsp'
require 'plugins.git'

use 'nvim-lua/plenary.nvim'
use 'nvim-telescope/telescope.nvim'
use 'jremmen/vim-ripgrep'
use 'thinca/vim-quickrun'
use 'joequery/Stupid-EasyMotion'
use 'yamatsum/nvim-cursorline'
use 'chrisbra/matchit'
